name: MulleSDE

on: [push]

env:
  BUILD_TYPE: release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: mulle-sde/github-ci@v1

    - name: Add to path
      run:  echo "$HOME/bin' >> $GITHUB_PATH

    - name: Dump Build Environment
      run:  env

    - name: Mulle-SDE Fetch
      shell: bash
      run: mulle-sde fetch 
      
    - name: Mulle-SDE Craft
      shell: bash
      run: mulle-sde test --${BUILD_TYPE}

    - name: Mulle-SDE Test
      shell: bash
      run: mulle-sde test
      
